language: python

matrix:
  include:

  - env: MODE=tests
    python: 3.4
    install: pip install coveralls tox
    script: tox
    after_success: coveralls

  - env: MODE=fedora:23
    services: [docker]
    install: make docker-build-images
    script: make docker-run-both

sudo: required
