dist: trusty

language: python

matrix:
  include:

  - env: MODE=tests
    python: 3.4
    before_install:
      - sudo add-apt-repository --yes ppa:mc3man/trusty-media
      - sudo apt-get update -qq
      - sudo apt-get install -qq ffmpeg
    install: pip install coveralls tox
    script: tox
    after_success: coveralls

  - env: MODE=tests without ffmpeg
    python: 3.4
    install: pip install tox
    script: tox

  - env: MODE=fedora:23
    services: [docker]
    install: make docker-build
    script: make docker-run

sudo: required
