# Dockerfile template for RPM linting and running py.test.
# $MODE, $NAME, and others are defined in .travis.yml and Makefile by envsubst.

FROM build/$MODE

ADD $NAME-$VERSION-*.rpm /build/

ENV LANG=en_US.utf8 LC_ALL=en_US.utf8

RUN dnf install -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm
RUN dnf install -y python3-httpretty python3-pytest $NAME-$VERSION-*.rpm
RUN pip3 install pytest-catchlog pytest-httpretty
RUN groupadd -r user && useradd -r -g user user
