# Dockerfile template for systemd testing and making sure RPM has needed dependencies.
# $MODE, $NAME, and others are defined in .travis.yml and Makefile by envsubst.

FROM $MODE

VOLUME /build
ADD $NAME-$VERSION-*.rpm /build/
WORKDIR /build

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y $NAME-$VERSION-*.rpm

CMD /lib/systemd/systemd
