# Dockerfile template for building RPMs.
# $MODE, $NAME, and others are defined in .travis.yml and Makefile by envsubst.

FROM robpol86/rpmdevtools-$MODE

VOLUME /build
ADD $NAME.spec README.rst /build/
WORKDIR /build

ENV MODE_MAJOR="$MODE_MAJOR" NAME="$NAME" SUMMARY="$SUMMARY" URL="$URL" VERSION="$VERSION"

RUN dnf builddep -y --spec $NAME.spec
RUN echo 'addFilter("E: dir-or-file-in-home")' >> /etc/rpmlint/config
